### ISSUE TITLE
Audio/Video Not recorded

### ISSUE THREAD

**Issue by nilaydave38** [aws-samples/amazon-chime-sdk-recording-demo#15] opened 2020-05-20 11:29 UTC
Hello Developer Team,

I had followed the same steps but was not able to record a video or audio.

Here is the sample mp4 file which is recorded the meeting.
[2020-05-20T09_32_26.zip](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/files/4656467/2020-05-20T09_32_26.zip)

We had shared the screen from the browser and also connected to audio devices but neither video nor audio was recorded.

Also, we want to record a video and audio with two devices.

AWS Chime API supports Video recording for android and ios 
   We used android and ios  
https://github.com/aws/amazon-chime-sdk-android
https://github.com/aws/amazon-chime-sdk-ios

If we want to achieve features like video calling conference and recording a complete conference with video how we can achieve this?

Please help.

Thank you

**Comment by aburnson** [comment] 2020-06-01 22:50
From the attached recording, looks like a duplicate of #8 where the Firefox "doorhanger" notification for their new encrypted DNS feature is getting in the way of the meeting starting. Going to close this issue as a duplicate of that.

> If we want to achieve features like video calling conference and recording a complete conference with video how we can achieve this?

We don't currently have a demo for that use case specifically, but speaking in general terms you would have:

1. A server-side meeting application - this would authenticate and authorize the mobile clients, call CreateMeeting/CreateAttendee and pass the responses to the clients to allow them to create and join a session. This application would also make the call to the recording infrastructure to start/stop recording.
2. Mobile client applications - these would communicate with the server application to get the meeting/attendee information and, if recording is user controlled, make requests to the server to start/stop recording.

To get more help for your specific use case, please contact AWS Support through the AWS console and open a ticket there.

**Closed by aburnson** 2020-06-01 22:50 UTC
