### ISSUE TITLE
Question: Is it posible to remove the "enable video" tile so the bot can record full screen?

### ISSUE THREAD

**Issue by robertbarron** [aws-samples/amazon-chime-sdk-recording-demo#75] opened 2021-03-12 21:36 UTC
Hello,

So I am wondering if there is a way to remove the "enable video" part from the bot, so it can record only the shared video of the attendee and not the one from the bot.

Thanks

![Captura de Pantalla 2021-03-12 a la(s) 15 28 54](https://user-images.githubusercontent.com/3171027/111000909-82300080-8348-11eb-88a7-83ed5dc00d5a.png)

**Comment by devalevenkatesh** [comment] 2021-03-15 18:14
Hello, it looks like the issue is with the Amazon Chime App and not with the Amazon Chime JS SDK. Sorry, but this repo is for the Amazon Chime JS SDK and we do not support the Amazon Chime app. Hence, request you to open a AWS support ticket for Amazon Chime or you can ask questions at https://answers.chime.aws/.

Additional Resources:
https://docs.aws.amazon.com/chime/latest/ug/chime-getting-support.html
https://answers.chime.aws/articles/139/free-trial-support.html

Closing this issue now.

**Closed by devalevenkatesh** 2021-03-15 18:14 UTC
