### ISSUE TITLE
Audio not recorded in version 2.2.0

### ISSUE THREAD

**Issue by junedlanja** [aws-samples/amazon-chime-sdk-recording-demo#60] opened 2020-12-01 12:33 UTC
I setup the environment as described. Everything is working fine recording is created in S3 bucket , screen and videos are captured perfectly but audio is missing. No audio is recorded at all. @anuranduttaroy

**Comment by wataruiijima** [comment] 2020-12-06 18:02
I had a similar problem, so I investigated and found that the latest version of amazon chime sdk serverless demo had no sound.
So I dropped the version of amazon chime sdk serverless demo down to tag version 1.22.0 and I was able to record.

`git clone https://github.com/aws/amazon-chime-sdk-js.git -b v1.22.0
`

I hope your problem is resolved as well.

**Comment by bpawlik** [comment] 2020-12-07 07:30
I solved it by increasing the sleep time at line 66 in recording/run.sh from 0.5 s to 3s.

**Comment by junedlanja** [comment] 2020-12-08 07:50
@wataruiijima You are right v1.22.0 is working. But its not working in 2.2.0

**Comment by ziyiz-amzn** [comment] 2020-12-17 18:12
This issue can be reproduced after v2.0.0. We will investigate and work on the fix.

**Comment by anuranduttaroy** [comment] 2020-12-17 21:44
Related: https://github.com/aws/amazon-chime-sdk-js/pull/958

**Comment by ziyiz-amzn** [comment] 2020-12-17 23:15
This issue was caused by a bug in amazon [aws/amazon-chime-sdk demo app](https://github.com/aws/amazon-chime-sdk-js/pull/958). It has been merged and will be available in v2.3.0.

Closing this issue and feel free to open if any further question.

**Closed by ziyiz-amzn** 2020-12-17 23:15 UTC
Labels: Bug
