### ISSUE TITLE
sam local testing ignores taskDefinition

### ISSUE THREAD

**Issue by pbrain19** [aws-samples/amazon-chime-sdk-recording-demo#110] opened 2021-11-12 00:54 UTC
Trying to test this locally and I noticed that that I keep getting this error 

```
{
    "message": "TaskDefinition not found.",
    "code": "ClientException",
    "time": "2021-11-12T00:03:53.033Z",
    "requestId": "d3cde11c-7f76-49f4-95f3-fe1ab311ac0f",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 30.375583669873564
}
```

This seems to be resulting of the start-api command completely ignoring the taskDefinition part of the template. I tried doing build as well before then

$ sam build  --template-file templates/RecordingDemoCloudformationTemplate.yaml  --parameter-overrides ECRDockerImageArn=70xxxxxx6936537074.dkr.ecr.us-west-2.amazonaws.com/video-recorder

it also failed the same way. Is there a way to test this task locally?

**Comment by ajselvar-work** [comment] 2021-11-17 06:43
Not able to reproduce the error. Were you following these steps node ./deploy.js -b recording-local -s recording-local -i 319849630214.dkr.ecr.us-east-1.amazonaws.com/recording-local -r us-east-1

**Comment by ajselvar-work** [comment] 2021-11-29 19:14
Closing due to no-activity. Please feel free to re-open if you need further help

**Closed** 2021-12-16 16:30 UTC
